name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Setup nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Style
        run: nix run github:tbidne/nix-hs-tools/0.6.1#nixpkgs-fmt -- --check

      - name: Build
        run: |
          nix build
          if [ -f "./result/share/fonts/truetype/RINGM___.TTF" ]; then
            echo "Build succeeded"
          else
            echo "Build failed"
            exit -1
          fi
