name: legacy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/fbfb79400a08bf754e32b4d4fc3f7d8f8055cf94.tar.gz

    - name: Build
      run: |
        nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/fbfb79400a08bf754e32b4d4fc3f7d8f8055cf94.tar.gz --arg pkgs 'import <nixpkgs> {}'
        if [ -f "./result/share/fonts/truetype/RINGM___.TTF" ]; then
            echo "Build succeeded"
        else
            echo "Build failed"
            exit -1
        fi
